@startuml checkout_sd_alternative
title UC 2.1.7 - Završetak kupovine (Alt: Greška pri kupovini)

actor Korisnik as U
participant "Frontend (React)" as FE
participant "Backend API (Express)" as BE
database "MySQL" as DB

U -> FE: Klik na "Završi kupovinu"
FE -> BE: POST /checkout
BE -> DB: Pokušaj kreiranja Order-a
DB --> BE: Greška / neuspeh upisa
BE --> FE: 500 Server Error
FE -> U: Prikaz poruke o grešci
@enduml
